apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 1.4.0
appVersion: 1.4.0
sources:
  - https://github.com/cyse7125-fall2022-group03/helm-chart.git
maintainers:
  - name: Ketki Kule
    email: kule.k@northeastern.edu
  - name: Sandeep Bharat Wagh
    email: wagh.sn@northeastern.edu
  - name: Vignesh Gunasekaran
    email: gunasekaran.v@northeastern.edu
